server:
  port: 10001

eureka:
  client:
    register-with-eureka: true

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/booker?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${mysql.user}
    password: ${mysql.password}
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/booker?serverTimezone=UTC&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 20
      connection-timeout: 5000
      leak-detection-threshold: 3000
      max-lifetime: 60000
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      use-sql-comments: false
      format-sql: true
      naming.physical-strategy: com.booker.core.config.jpa.JpaPhysicalNamingStrategy
      jakarta:
        persistence:
          jdbc:
            url: jdbc:mysql://localhost:3306/booker?serverTimezone=UTC&characterEncoding=UTF-8