server:
  port: 10001

eureka:
  client:
    register-with-eureka: true

spring:
  application:
    name: user-service
  datasource:
    hikari:
      write:
        url: jdbc:mysql://127.0.0.1:3306/booker
        username: ${mysql.user}
        password: ${mysql.password}
        driver-class-name: com.mysql.cj.jdbc.Driver
      read:
        url: jdbc:mysql://127.0.0.1:3306/booker
        username: ${mysql.user}
        password: ${mysql.user.password}
        driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        show_sql: true
        use_sql_comments: false
        format_sql: true
        physical_naming_strategy: com.booker.core.config.jpa.JpaPhysicalNamingStrategy