server:
  port: 10001

eureka:
  client:
    register-with-eureka: true

spring:
  application:
    name: user-service
  datasource:
    hikari:
      write:
        jdbc-url: jdbc:mysql://127.0.0.1:3306/booker?serverTimezone=UTC&characterEncoding=UTF-8
        username: ${mysql.user}
        password: ${mysql.password}
        driver-class-name: com.mysql.cj.jdbc.Driver
      read:
        jdbc-url: jdbc:mysql://127.0.0.1:3306/booker?serverTimezone=UTC&characterEncoding=UTF-8
        username: ${mysql.user}
        password: ${mysql.password}
        driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      use-sql-comments: false
      format-sql: true
      naming.physical-strategy: com.booker.core.config.jpa.JpaPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      jakarta:
        persistence:
          jdbc:
            url: jdbc:mysql://127.0.0.1:3306/booker?serverTimezone=UTC&characterEncoding=UTF-8