server:
  port: 10001

eureka:
  client:
    register-with-eureka: true

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booker?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${mysql.user}
    password: ${mysql.password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  pattern:
    console: "[%-5level] %d{yy-MM-dd HH:mm:ss} [%logger{0}:%line] - %msg%n"
  level:
    org:
      springframework: DEBUG